server:
  port: 8080
spring:
  application:
    name: oauth
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        ip: 127.0.0.1
        group: gatewaynacos
        namespace: demo
