server:
  port: 9098
spring:
  application:
    name: serviceone
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        ip: 127.0.0.1
        group: gatewaynacos
        namespace: demo
