server:
  port: 13008
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enable: true
          lower-case-service-id: true
      routes:
        - id: serviceone
          uri: lb://serviceone
          predicates:
            - Path=/serviceone/**
        - id: servicetwo
          uri: lb://servicetwo
          predicates:
            - Path=/servicetwo/**
    loadbalancer:
      retry:
        enabled: true
