server:
  port: 13008
spring:
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.50.181:8848
        ip: 127.0.0.1
        group: gatewaynacos
        namespace: demo
    gateway:
      locator:
        enable: true
        lower-case-service-id: true
      routes:
        - id: serviceone
          uri: lb://serviceone
          predicates:
            - Path=/serviceone/**
        - id: servicetwo
          uri: lb://servicetwo
          predicates:
            - Path=/servicetwo/**
